# 3. 신경망
* * *

## 3.3 다차원 배열의 계산

##### <br><br><span style="color: mediumaquamarine;">**다차원 배열**</spen>
+ <spen style="color: gold;">**다차원 배열**</spen> == 숫자의 집합
    + 숫자가 한 줄로 늘어선 것
    + 직사각형으로 늘어놓은 것
    + 3차원으로 늘어놓은 것
    + ( 더 일반화한 ) N차원으로 나열하는 것

In [1]:
import numpy as np

A = np.array([1, 2, 3, 4])
print("A = ", A)
print(np.ndim(A)) # 배열의 차원 수
print(A.shape) # 배열의 형상 ( 튜플로 반환함 : 다차원 배열일 때와 통일된 형태로 결과를 반환하기 위해 ) <- 원소의 개수
print(A.shape[0])

A =  [1 2 3 4]
1
(4,)
4


In [2]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)
print(np.ndim(B))
print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


+ <spen style="color: gold;">**2차원 배열**</spen> == 행렬 ( matrix ) ← 가로 == 행 ( row ), 세로 == 열 ( column )
    + 처음 차원 원소 3개 ( 0번째 차원 )
    + 다음 차원 원소 2개 ( 1번째 차원 )
</br></br>
<img src="../img/matrix.png" width='300'>

##### <br><br><span style="color: mediumaquamarine;">**행렬의 곱**</spen>
행렬의 곱 계산 방법  
<img src="../img/matrix_multiplication.png" width='1000'>

+ 왼쪽 행렬의 행 ( 가로 ) 과 오른쪽 행렬의 열 ( 세로 ) 을 원소별로 곱하고 그 값들을 더해서 계산

In [3]:
A = np.array([[1, 2], [3, 4]])
print(A.shape)
B = np.array([[5, 6], [7, 8]])
print(B.shape)
print(np.dot(A, B))

(2, 2)
(2, 2)
[[19 22]
 [43 50]]


+ A && B == 2 X 2 행렬
+ ```np.dot()``` == 입력이 1차원 배열이면 벡터, 2차원 배열이면 행렬 곱을 계산
    + ```np.dot(A, B)``` != ```np.dot(B, A)```

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.shape)
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B.shape)
print(np.dot(A, B))

(2, 3)
(3, 2)
[[22 28]
 [49 64]]


+ <spen style="color: palevioletred;">**행렬의 형상 ( shape ) 주의**</spen>
    + 행렬 A의 1번째 차원의 원소 수 ( 열 수 ) == 행렬 B의 0번째 차원의 원소 수 ( 행 수 )
    + 다르면 행렬의 곱을 계산할 수 없음

In [ ]:
C = np.array([[1, 2], [3, 4]])
print(C.shape)
print(A.shape)

# print(np.dot(A, C)) # 행렬의 형상이 다르므로 오류 발생
"""
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[16], line 4
      2 print(C.shape)
      3 print(A.shape)
----> 4 print(np.dot(A, C)) # 행렬의 형상이 다르므로 오류 발생

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)
"""

(2, 2)
(2, 3)


'\n---------------------------------------------------------------------------\nValueError                                Traceback (most recent call last)\nCell In[16], line 4\n      2 print(C.shape)\n      3 print(A.shape)\n----> 4 print(np.dot(A, C)) # 행렬의 형상이 다르므로 오류 발생\n\nValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)\n'

행렬 A의 1번째 차원의 원소 수 ( 열 수 ) != 행렬 B의 0번째 차원의 원소 수 ( 행 수 )

3 X 2 행렬 A와 2 X 4 행렬 B를 곱해 3 X 4 행렬 C를 만드는 예  

<img src="../img/matrix_shape1.png" width="600">

+ 계산 결과인 행렬 C의 형상은 == ( 행렬 A의 행 수, B의 열 수 )

</br>&nbsp;</br>
2차원 행렬X1차원 배열일 때도 대응하는 차원의 원소 수를 일치시켜야 한다.  

<img src="../img/matrix_shape2.png" width="600">

In [6]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A.shape)
B = np.array([7, 8])
print(B.shape)
print(np.dot(A, B))

(3, 2)
(2,)
[23 53 83]


##### <br><br><span style="color: mediumaquamarine;">**신경망에서의 행렬 곱**</spen>

<img src="../img/neural_network_matrix1.png" width="800">

+ 위의 신경망은 편향과 활성화 함수를 생략하고 가중치만 가지고 있음
+ X와 W의 대응하는 차원의 원소수가 같아야함

In [7]:
X = np.array([1, 2])
print(X.shape)
W = np.array([[1, 3, 5], [2, 4, 6]])
print(W)
print(W.shape)
Y = np.dot(X, W)
print(Y)

(2,)
[[1 3 5]
 [2 4 6]]
(2, 3)
[ 5 11 17]


+ 행렬의 곱으로 한꺼번에 계산해주는 기능 ( ```np.dot()``` ) 은 신경망을 구현할 때 매우 중요함