# 3. 신경망
* * *

+ 퍼셉트론으로 복잡한 함수도 표현할 수 있음
+ 그러나, 가중치를 설정하는 작업 ( 원하는 결과를 출력하도록 가중치 값을 적절히 정하는 작업 ) 은 여전히 사람이 수동으로 해야함
</br></br>
+ 신경망의 중요한 성질 == 가중치 매개변수의 적절한 값을 데이터로부터 잗ㅇ으로 학습하는 능력

## 3.4 3층 신경망 구현하기

+ 3층 신경망에서 수행되는 입력 ~ 출력까지의 처리 ( 순방향 처리 ) 를 구현함

</br>&nbsp;</br>
3층 신경망  
<img src="../img/neural_network_3floor.png" width='600'>

+ 입력층 ( 0층 ) 뉴런 2개
+ 첫 번째 은닉층 ( 1층 ) 뉴런 3개
+ 두 번째 은닉층 ( 2층 ) 뉴런 2개
+ 출력층 ( 3층 ) 뉴런 2개

##### <br><br><span style="color: mediumaquamarine;">**표기법 설명**</spen>
+ 신경망에서의 계산은 행렬 계산으로 정리할 수 있다.
+ 신경망 각 층의 계산은 행렬의 곱으로 처리할 수 있다.

중요한 표기  
<img src="../img/neural_network_matrix2.png" width='600'>

+ $^{(1)}$ == 1층의 가중치, 1층의 뉴런임을 뜻하는 번호
+ $_{1 2}$ == 다음 층 뉴런 && 앞 층 뉴런

##### <br><br><span style="color: mediumaquamarine;">**각 층의 신호 전달 구현하기**</spen>

<img src="../img/neural_network_matrix3.png" width='600'>

$a^{(1)}_1 = w^{(1)}_{11}x_1 + w^{(1)}_{12}x_2 + b^{(1)}_1$
+ 행렬의 곱을 이용하면 1층의 '가중치 부분'을 아래와같이 간소화 할 수 있음

$A^{(1)} = XW^{(1)} + B^{(1)}$

$$
A^{(1)} = (a^{(1)}_1 a^{(1)}_2 a^{(1)}_3), \quad X = (x_1 x_2), \quad B^{(1)} = (b^{(1)}_1 b^{(1)}_2 b^{(1)}_3), \quad 
W^{(1)} = \begin{pmatrix}
w^{(1)}_{11} w^{(1)}_{21} w^{(1)}_{31}\\\\
w^{(1)}_{12} w^{(1)}_{22} w^{(1)}_{32}
\end{pmatrix}
$$

In [1]:
import numpy as np

X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(W1.shape)
print(X.shape)
print(B1.shape)

A1 = np.dot(X, W1) + B1
print(A1)

(2, 3)
(2,)
(3,)
[0.3 0.7 1.1]


입력층에서 1층으로 신호 전달  
<img src="../img/neural_network_matrix4.png" width='600'>

+ 은닉층에서 가중치 합 ( 가중 신호와 편향의 총합 ) 을 $a$로 표기하고 활성화 함수 $h()$로 변환된 신호를 $z$로 표기

In [2]:
from fucntion import sigmoid

Z1 = sigmoid(A1)

print(A1)
print(Z1)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


1층에서 2층으로의 신호 전달  
<img src="../img/neural_network_matrix5.png" width='600'>

In [3]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

A2 = np.dot(Z1, W2) + B2 # 1층의 출력이 2층의 입력이 됨 ( Z1 )
Z2 = sigmoid(A2)

print(A2)
print(Z2)

(3,)
(3, 2)
(2,)
[0.51615984 1.21402696]
[0.62624937 0.7710107 ]


2층에서 출력층으로 신호 전달  
<img src="../img/neural_network_matrix6.png" width='600'>

+ 활성화 함수만 은닉층과 다름
+ 출력층의 활성화 함수를 $\sigma()$로 표시하여 은닉층의 활성화 함수 $h()$와 다름을 명시

In [4]:
# 항등 함수
def identity_function(x):
    return x

W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3) # || Y = A3

print(A3)
print(Y)

[0.31682708 0.69627909]
[0.31682708 0.69627909]


+ 회귀 == 항등함수
+ 2클래스 분류 == 시그모이드 함수
+ 다중 클래스 분류 == 소프트맥스 함수

##### <br><br><span style="color: mediumaquamarine;">**구현 정리**</spen>
+ <spen style="color: palevioletred;">**신경망 관례**</spen>
    + 가중치 == 대문자
    + 그 외 편향과 중간 결과 등 == 소문자

3층 신경망 구현 정리

In [5]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])

    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b2
    y = identity_function(a3)

    return y
network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)

[0.31682708 0.69627909]


+ ```init_network()``` 함수 == 가중치와 편향을 초기화하고 이들을 딕셔너리 변수인 ```network```에 저장
+ ```forward()``` 함수 == 입력 신호를 출력으로 변환하는 처리 과정을 모두 구현
    + 신경망의 순방향 ( 입력에서 출력 방향) 구현 ← 순전파